### ISSUE TITLE
pyramid_chart lost half tag

### ISSUE THREAD

**Issue by LenmonChen** [thomas-neitmann/ggcharts#80]
Hi guys,
I really appreciate your  ggcharts package.
But a bug occur to me.
When I try pyramid_chart with geom_text(), it lost the  left half tagg.

Here is the code：
`
data(popch)
options(scipen = 999)
pyramid_chart(popch, age, pop, sex, xlab = "Population", title = "Switzerland 2020") +
geom_text(aes(label=round(pop/10000,2))) 
`

**Comment by thomas-neitmann** [comment]
The problem is that `pyramid_chart()` creates two individual `ggplots` and combines them with `{patchwork}`. If you use `+` with a `patchwork` it will only add to the last plot which in case of `pyramid_chart()` is the right one. You can either use `&` instead of `+` or you add `geom_text()` to each individual plot.

First option using `&`:
```
data(popch)
options(scipen = 999)
pyramid_chart(popch, age, pop, sex, xlab = "Population", title = "Switzerland 2020") &
  geom_text(aes(label=round(pop/10000,2)))
```

Second option:
```r
data(popch)
options(scipen = 999)
plot <- pyramid_chart(popch, age, pop, sex, xlab = "Population", title = "Switzerland 2020")
plot[[1]] <- plot[[1]] + geom_text(aes(label=round(pop/10000,2)))
plot[[2]] <- plot[[2]] + geom_text(aes(label=round(pop/10000,2)))
plot
```

In this case the first option works well but your mileage may vary in other cases.
